- include: setup.yml
- include: nginx.yml
- include: certificates.yml

- name: Install cronjob for key generation
  cron:
    job: "cd {{ acme_tiny_data_directory }} && ./renew-certs.py"
    day: "{{ letsencrypt_cronjob_daysofmonth }}"
    hour: 4
    minute: 30
    state: present
    name: letsencrypt certificate renewal
